export const REQUEST = "REQUEST";
export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";

export const GET_TODO_LIST = "GET_TODO_LIST";
export const ADD_TODO_TO_DB = "ADD_TODO_TO_DB";
export const DELETE_TODO_FROM_DB = "DELETE_TODO_FROM_DB";
export const DELETE_COMPLETED_FROM_DB = "DELETE_COMPLETED_FROM_DB";

export const DELETE_TODO = "DELETE_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const DELETE_COMPLETED = "DELETE_COMPLETED";

export const FIND_TODO = "FIND_TODO";

export const VISIBILITY = {
  SHOW_ALL: "SHOW_ALL",
  SHOW_ACTIVE: "SHOW_ACTIVE",
  SHOW_COMPLETED: "SHOW_COMPLETED",
};

export const SET_FIND_TODO_TEXT = "SET_FIND_TODO_TEXT";
export const RESET_FIND_TODO_TEXT = "RESET_FIND_TODO_TEXT";